-- Baseline schema migration for bank_categorizer.
--
-- This captures the schema exactly as it was already being generated by Hibernate
-- (spring.jpa.hibernate.ddl-auto=update/create-drop) from the current entity model
-- (Category, Transaction) at the time Flyway was introduced (US-7). From this point on,
-- schema changes are made via new versioned migration files in this directory rather than
-- relying on Hibernate to create/alter the schema in any profile.

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE category_keywords (
    category_id BIGINT NOT NULL,
    keyword     VARCHAR(255) NOT NULL,
    CONSTRAINT pk_category_keywords PRIMARY KEY (category_id, keyword),
    CONSTRAINT fk_category_keywords_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE TABLE transactions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date        DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    amount      NUMERIC(19, 2) NOT NULL,
    category_id BIGINT,
    CONSTRAINT fk_transactions_category FOREIGN KEY (category_id) REFERENCES categories (id)
);

CREATE INDEX idx_transactions_date ON transactions (date);
CREATE INDEX idx_transactions_category_id ON transactions (category_id);
