-- Switch categories.id and transactions.id from IDENTITY generation to a plain
-- database sequence with a default of nextval(...).
--
-- IDENTITY columns require Hibernate to fetch the generated key immediately after each
-- insert, which prevents JDBC batching of saveAll(...) calls (e.g. TransactionImportService
-- importing a CSV/XLSX, DefaultCategorySeeder seeding default categories). A sequence-backed
-- id with a client-side allocation size of 1 preserves the same contiguous-id behavior while
-- allowing batched inserts.

-- Drop identity generation (this also drops the internal sequence Postgres created for
-- "GENERATED BY DEFAULT AS IDENTITY" in V1__baseline_schema.sql), then create an explicit,
-- ordinary sequence in its place.
ALTER TABLE categories ALTER COLUMN id DROP IDENTITY IF EXISTS;
ALTER TABLE transactions ALTER COLUMN id DROP IDENTITY IF EXISTS;

CREATE SEQUENCE categories_id_seq;
CREATE SEQUENCE transactions_id_seq;

-- Position each sequence past the highest existing id (or at 1 for an empty table) so
-- existing rows' ids can never collide with a newly generated one.
SELECT setval('categories_id_seq', COALESCE((SELECT MAX(id) FROM categories), 0) + 1, false);
SELECT setval('transactions_id_seq', COALESCE((SELECT MAX(id) FROM transactions), 0) + 1, false);

ALTER TABLE categories ALTER COLUMN id SET DEFAULT nextval('categories_id_seq');
ALTER TABLE transactions ALTER COLUMN id SET DEFAULT nextval('transactions_id_seq');

ALTER SEQUENCE categories_id_seq OWNED BY categories.id;
ALTER SEQUENCE transactions_id_seq OWNED BY transactions.id;
